version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 13
    allow:
      - dependency-type: "development"
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 5

  - package-ecosystem: "cargo"
    directory: "/playground/wasm"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 13
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 13
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 5
