[package]
name = "js-semver-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.js-semver]
path = ".."

[[bin]]
name = "version"
path = "fuzz_targets/version.rs"
test = false
doc = false
bench = false

[[bin]]
name = "range"
path = "fuzz_targets/range.rs"
test = false
doc = false
bench = false

[[bin]]
name = "pathological"
path = "fuzz_targets/pathological.rs"
test = false
doc = false
bench = false
