[package]
name = "js-semver-website-wasm"
version = "0.1.0"
edition = "2024"
description = "Wasm bindings for the js-semver website"
license = "MIT-0"
repository = "https://github.com/ryuapp/js-semver"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
js-semver = { path = "../.." }
wasm-bindgen = "^0.2.122"

[package.metadata.wasm-pack.profile.custom]
wasm-opt = ["-Oz", "--enable-bulk-memory"]
